project 'SlimeSoccerSwift.xcodeproj/'
platform :osx, '10.13'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SlimeSoccerSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Pods for SlimeSoccerSwift
  pod 'Birdsong', '~> 0.6'

end
